name: botyo
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - ld_impl_linux-aarch64=2.40
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libnsl=2.0.1
  - libsqlite=3.45.1
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.2.13
  - ncurses=6.4.20240210
  - openssl=3.2.1
  - pip=24.0
  - python=3.11.7
  - readline=8.2
  - setuptools=69.0.3
  - tk=8.6.13
  - wheel=0.42.0
  - xz=5.2.6
  - pip:
      - annotated-types==0.7.0
      - anyio==4.12.1
      - appdirs==1.4.4
      - apscheduler==3.10.4
      - arrow==1.4.0
      - authlib==1.6.6
      - beautifulsoup4==4.14.3
      - beets==1.6.0
      - better-exceptions==0.3.3
      - boto3==1.34.41
      - botocore==1.34.162
      - cachable==0.3.54
      - cachecontrol==0.14.4
      - cairocffi==1.7.1
      - cairosvg==2.7.1
      - certifi==2026.1.4
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - checksumdir==1.3.0
      - click==8.3.1
      - colorama==0.4.6
      - confuse==2.1.0
      - corefile==0.1.18
      - coreimage==0.5.0
      - corelog==0.0.22
      - corestring==0.3.19
      - corethread==0.1.3
      - coretime==0.1.5
      - cryptography==46.0.3
      - cssselect2==0.8.0
      - cytoolz==1.1.0
      - dataclasses-json==0.5.14
      - defusedxml==0.7.1
      - einops==0.8.1
      - emoji==2.10.1
      - emoji-country-flag==2.1.0
      - facenet-pytorch==20.5.2
      - fastapi==0.109.2
      - filelock==3.20.2
      - filetype==1.2.0
      - firebase-admin==7.1.0
      - flake8==7.3.0
      - fs==20.4.16
      - fsspec==2025.12.0
      - fuzzelinho==0.3.1
      - google-api-core==2.28.1
      - google-auth==2.47.0
      - google-cloud-core==2.5.0
      - google-cloud-firestore==2.22.0
      - google-cloud-storage==3.7.0
      - google-crc32c==1.8.0
      - google-resumable-media==2.8.0
      - googleapis-common-protos==1.72.0
      - grpcio==1.76.0
      - grpcio-status==1.76.0
      - h11==0.16.0
      - h2==4.3.0
      - hf-xet==1.2.0
      - hiredis==3.3.0
      - hpack==4.1.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - hyperframe==6.1.0
      - idna==3.11
      - jellyfish==1.2.1
      - jinja2==3.1.6
      - jmespath==1.0.1
      - kornia==0.8.2
      - kornia-rs==0.1.10
      - levenshtein==0.27.3
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - marshmallow==3.26.2
      - mccabe==0.7.0
      - mdurl==0.1.2
      - mediafile==0.14.0
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multiavatar==1.0.3
      - munkres==1.1.4
      - musicbrainzngs==0.7.1
      - mutagen==1.47.0
      - mypy-extensions==1.1.0
      - networkx==3.6.1
      - numpy==2.2.6
      - olefile==0.47
      - opencv-python==4.12.0.88
      - packaging==25.0
      - peewee==3.17.1
      - pillow==12.1.0
      - pilmoji==2.0.4
      - pixelme==0.6.2
      - progressor==1.0.16
      - prompt-toolkit==3.0.52
      - proto-plus==1.27.0
      - protobuf==6.33.2
      - psycopg2==2.9.9
      - py-avataaars==1.1.2
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycodestyle==2.14.0
      - pycountry==24.6.1
      - pycparser==2.23
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyemoji==1.0.4
      - pyfiglet==1.0.4
      - pyflakes==3.4.0
      - pygments==2.19.2
      - pyjwt==2.10.1
      - pyotp==2.9.0
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.9
      - python-twitter-v2==0.9.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - questionary==2.1.1
      - random-user-agent==1.0.1
      - rapidfuzz==3.14.3
      - redis==7.1.0
      - regex==2025.11.3
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - rich==14.2.0
      - rsa==4.9.1
      - s3transfer==0.10.4
      - safetensors==0.7.0
      - segno==1.6.6
      - semver==3.0.4
      - shellingham==1.5.4
      - six==1.17.0
      - soupsieve==2.8.1
      - spandrel==0.4.1
      - starlette==0.36.3
      - stringcase==1.2.0
      - structlog==25.5.0
      - sympy==1.14.0
      - tabulate==0.9.0
      - term-image==0.8.0.3
      - texttable==1.7.0
      - timm==1.0.24
      - tinycss2==1.5.1
      - tokenizers==0.22.2
      - toolz==1.1.0
      - torch==2.9.1
      - torchvision==0.24.1
      - tqdm==4.67.1
      - transformers==4.57.3
      - typer==0.21.1
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - tzlocal==5.3.1
      - unidecode==1.3.8
      - urllib3==2.6.3
      - uvicorn==0.27.1
      - uvloop==0.19.0
      - validators==0.22.0
      - wcwidth==0.2.14
      - webencodings==0.5.1
      - wikipedia==1.4.0
      - you-get==0.4.1650
prefix: /store/home/jago/miniforge3/envs/botyo
